import "dotenv/config"
import { PrismaClient } from "../src/generated/prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"

const p = new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL!})})

const updates = [
  ["005", "005 (特工005)", "005", "Sega", 1981, "SEGA于1981年推出的街机潜行游戏，玩家扮演特工005躲避敌人送交公文包。"],
  ["aaf-mtang", "US AAF Mustang", "US AAF Mustang", "NMK", 1990, "NMK开发的纵版射击游戏，玩家驾驶美国战斗机击落敌机。"],
  ["astro-blaster", "星际炮手", "Astro Blaster", "Gremlin/Sega", 1981, "Gremlin/Sega推出的固定射击游戏，首创街机语音合成，玩家需管理激光温度和燃料。"],
  ["ataxx", "阿塔克斯", "Ataxx", "Leland", 1990, "Leland发行的双轨迹球对战益智游戏，翻转对手棋子占领全盘。"],
  ["bosconian", "波斯克尼亚", "Bosconian", "Namco", 1981, "Namco推出的多方向卷轴射击游戏，首创雷达系统和接关功能。"],
  ["bubbles", "泡泡", "Bubbles", "Williams", 1982, "Williams推出的迷宫动作游戏，玩家操控肥皂泡收集物品并躲避敌人。"],
  ["centipede", "蜈蚣", "Centipede", "Atari", 1981, "Atari经典固定射击游戏，玩家操控炮台射击下落的蜈蚣。"],
  ["combat", "战斗", "Combat", "Atari", 1977, "Atari 2600首发游戏，坦克对战模拟。"],
  ["crossbow", "十字弓", "Crossbow", "Exidy", 1983, "Exidy推出的光枪射击游戏，玩家射击敌人营救队友。"],
  ["cyberball", "赛博球", "Cyberball", "Atari", 1989, "Atari推出的未来风格橄榄球游戏，机器人球员持球达阵得分。"],
  ["gun-smoke", "荒野大镖客", "Gun Smoke", "Capcom", 1985, "Capcom推出的西部题材纵版射击游戏，玩家扮演赏金猎人在西部荒野剿匪。"],
  ["jackal", "赤影战士", "Jackal", "Konami", 1986, "Konami推出的俯视角射击游戏，玩家驾驶吉普车营救战俘。"],
  ["vigilante", "街头 vigilante", "Vigilante", "Irem", 1988, "Irem推出的横版清关游戏，玩家扮演义警在街头打击犯罪。"],
  ["vendetta", "罪恶街头", "Vendetta", "Konami", 1991, "Konami推出的横版清关游戏，四人组队打击犯罪组织。"],
  ["hang-on", "摩托车", "Hang-On", "Sega", 1985, "Sega推出的摩托车竞速游戏，采用体感框体设计。"],
  ["twinbee", "兵蜂", "TwinBee", "Konami", 1985, "Konami推出的卡通风格纵版射击游戏，双人合作收集铃铛升级武器。"],
  ["x-men", "X战警", "X-Men", "Konami", 1992, "Konami推出的6人合作横版清关游戏，可选金刚狼等变种人对抗万磁王。"],
  ["robocop", "机械战警", "RoboCop", "Data East", 1988, "Data East推出的横版射击游戏，改编自同名电影，玩家扮演机械战警打击犯罪。"],
  ["willow", "威洛", "Willow", "Capcom", 1989, "Capcom推出的横版动作游戏，改编自同名电影，玩家扮演巫师冒险。"],
  ["thunder-blade", "雷刃", "Thunder Blade", "Sega", 1987, "Sega推出的伪3D直升机射击游戏，采用体感框体。"],
  ["green-beret", "绿色贝雷帽", "Green Beret", "Konami", 1985, "Konami推出的横版射击游戏，玩家扮演特种兵深入敌后营救战友。"],
  ["blasted", "爆破手", "Blasted", "Brooklyn Games", 1992, "纵版射击游戏，玩家操控战机击落敌机。"],
  ["blasto", "爆破人", "Blasto", "Gremlin/Sega", 1982, "固定射击游戏，玩家操控飞船抵御外星入侵。"],
  ["blaze-on", "火焰之路", "Blaze On", "Jaleco", 1983, "赛车竞速游戏，躲避障碍物抵达终点。"],
  ["block-block", "打砖块", "Block Block", "Capcom", 1990, "打砖块类益智游戏，操控挡板反弹小球击碎砖块。"],
  ["bloxeed", "宝石方块", "Bloxeed", "Sega", 1989, "俄罗斯方块变体益智游戏。",],
  ["body-slam", "摔跤大赛", "Body Slam", "Technos", 1986, "职业摔跤对战游戏，支持双人对战。"],
  ["bombjack-twin", "炸弹杰克双子星", "Bomb Jack Twin", "NMK", 1993, "双人合作平台动作游戏，收集炸弹躲避敌人。"],
  ["break-thru", "突破", "Break Thru", "Data East", 1986, "Data East推出的纵版射击游戏，玩家驾驶装甲车突破敌军防线。"],
  ["burning-force", "燃烧力量", "Burning Force", "Namco", 1989, "Namco推出的伪3D射击游戏，玩家驾驶战机在太空中战斗。"],
  ["cadillacs-kyouryuu-shinseiki", "恐龙快打", "Cadillacs and Dinosaurs", "Capcom", 1993, "Capcom推出的横版清关游戏，改编自漫画，玩家在末日世界对抗邪恶势力。"],
  ["darwin-4078", "达尔文4078", "Darwin 4078", "Data East", 1986, "Data East推出的纵版射击游戏，玩家操控战机进化升级。"],
  ["double-dribble", "双 dribble", "Double Dribble", "Konami", 1986, "Konami推出的篮球游戏，以精彩的扣篮动画闻名。"],
  ["growl", "森林守护神", "Growl", "Taito", 1991, "Taito推出的横版清关游戏，玩家扮演护林员打击盗猎者。"],
  ["ikki", "一揆", "Ikki", "Sunsoft", 1985, "Sunsoft推出的搞笑风格动作游戏，农民起义对抗压迫者。"],
  ["kageki", "火激", "Kageki", "Taito", 1988, "Taito推出的横版清关游戏，Q版角色打击黑帮。"],
  ["blaze-on", "火焰之路", "Blaze On", "Jaleco", 1983, "赛车竞速躲避障碍物。"],
  ["cadash", "卡达什", "Cadash", "Taito", 1989, "Taito推出的横版动作RPG，融合角色扮演与平台动作元素。"],
  ["chase-h-q", "追捕HQ", "Chase H.Q.", "Taito", 1988, "Taito推出的警匪追逐赛车游戏，追捕逃犯。"],
  ["circ-charlie", "马戏团查理", "Circus Charlie", "Konami", 1984, "Konami推出的马戏团主题平台动作游戏。"],
  ["cyvern", "赛文", "Cyvern", "Kaneko", 1998, "Kaneko推出的纵版射击游戏，龙骑士题材。"],
  ["dragonball-z", "龙珠Z", "Dragon Ball Z", "Banpresto", 1993, "Banpresto推出的龙珠题材2D格斗游戏。"],
  ["giga-wing", "Giga Wing", "Giga Wing", "Capcom", 1999, "Capcom推出的纵版弹幕射击游戏，反射护盾系统。"],
  ["gun-smoke", "荒野大镖客", "Gun Smoke", "Capcom", 1985, "西部题材纵版射击游戏。"],
  ["macross-pl", "超时空要塞", "Macross", "NMK", 1992, "超时空要塞题材纵版射击游戏。"],
  ["metal-hawk", "金属猎鹰", "Metal Hawk", "Namco", 1988, "Namco推出的直升机射击游戏。"],
  ["mvp", "MVP棒球", "MVP", "Sega", 1989, "Sega推出的街机棒球游戏。"],
  ["ninja-emaki", "忍者绘卷", "Ninja Emaki", "UPL", 1985, "UPL推出的横版忍者动作游戏。"],
  ["ninja-spirit", "忍者魂", "Ninja Spirit", "Irem", 1988, "Irem推出的横版忍者动作射击游戏。"],
  ["puyo-puyo-2", "魔法气泡2", "Puyo Puyo 2", "Compile", 1994, "经典方块对战益智游戏续作。"],
  ["riot", "暴动", "Riot", "NMK", 1992, "NMK推出的动作射击游戏。"],
  ["riot-city", "暴动城市", "Riot City", "Technos", 1991, "Technos推出的横版清关游戏。"],
  ["shadowland", "影之传说", "Shadowland", "Namco", 1987, "Namco推出的横版动作游戏，玩家扮演忍者拯救公主。"],
  ["shanghai-ii", "上海II", "Shanghai II", "Success", 1989, "麻将配对消除益智游戏。"],
  ["silent-dragon", "沉默之龙", "Silent Dragon", "Taito", 1992, "Taito推出的忍者题材横版清关游戏。"],
  ["superman", "超人", "Superman", "Taito", 1988, "Taito推出的横版动作游戏，玩家扮演超人打击犯罪。"],
  ["three-wonders", "三个奇迹", "Three Wonders", "Capcom", 1991, "Capcom推出的三个迷你游戏合集：射击、平台、解谜。"],
  ["tough-turf", "暴力橄榄球", "Tough Turf", "Sega", 1987, "Sega推出的街头橄榄球对战游戏。"],
  ["turbo", "极速赛车", "Turbo", "Sega", 1981, "Sega推出的赛车游戏。"],
  ["twin-hawk", "双鹰", "Twin Hawk", "Toaplan", 1990, "Toaplan推出的纵版射击游戏。"],
  ["u-n-squadron", "战区88", "U.N. Squadron", "Capcom", 1989, "Capcom推出的横版射击游戏，改编自动漫战区88。"],
  ["v-five", "V5战机", "V-Five", "Capcom", 1993, "Capcom推出的纵版射击游戏。"],
  ["vandyke", "范戴克", "Vandyke", "UPL", 1991, "UPL推出的纵版射击游戏。"],
  ["vigilante", "义警", "Vigilante", "Irem", 1988, "Irem推出的横版清关游戏，玩家扮演义警打击街头犯罪。"],
  ["xexex", "XEXEX", "Xexex", "Konami", 1991, "Konami推出的横版射击游戏，以精美的像素画面和独特的子机系统闻名。"],
  ["youjyuden", "妖兽传", "Youjyuden", "Irem", 1986, "Irem推出的横版动作游戏。"],
  ["xybots", "XY机器人", "Xybots", "Atari", 1987, "Atari推出的3D视角射击游戏，玩家操控机器人在迷宫中战斗。"],
  ["gradi-iii", "宇宙巡航机III", "Gradius III", "Konami", 1989, "Konami推出的横版射击游戏，宇宙巡航机系列第三作。"],
  ["gunforce-2", "钢炮部队2", "Gunforce 2", "Irem", 1994, "Irem开发的横版射击游戏，合金弹头精神前作。"],
  ["haunted-castle", "恶魔城", "Haunted Castle", "Konami", 1988, "Konami推出的恶魔城系列街机版，玩家扮演吸血鬼猎人闯关。"],
  ["metal-clash", "机甲大战", "Metal Clash", "Nihon Bussan", 1986, "机甲题材格斗对战游戏。"],
  ["sky-smasher", "天空粉碎者", "Sky Smasher", "Nichibutsu", 1984, "纵版射击游戏，玩家驾驶战机击落敌机。"],
  ["super-x", "超级X", "Super X", "Williams", 1983, "Williams推出的纵版射击游戏。"],
  ["720-degrees", "720度", "720 Degrees", "Atari", 1986, "Atari推出的滑板主题动作游戏，玩家在公园中完成特技动作。"],
  ["battlecry", "战吼", "Battlecry", "Nichibutsu", 1985, "纵版射击游戏。"],
  ["beezer", "蜜蜂", "Beezer", "Sega", 1980, "Sega推出的射击游戏。"],
  ["blast-off", "发射", "Blast Off", "Sega", 1979, "Sega推出的射击游戏。"],
  ["blazing-tornado", "烈火龙卷", "Blazing Tornado", "NMK", 1994, "纵版射击游戏。"],
  ["borench", "深穴冒险", "Borench", "Data East", 1985, "Data East推出的平台动作游戏。"],
  ["bullet", "子弹", "Bullet", "Sega", 1985, "射击游戏。"],
  ["bullfight", "斗牛", "Bullfight", "Sega", 1989, "斗牛模拟游戏。"],
  ["caliber-50", "50口径", "Caliber 50", "Jaleco", 1988, "垂直射击游戏。"],
  ["canyon-bomber", "峡谷轰炸机", "Canyon Bomber", "Atari", 1977, "Atari推出的轰炸模拟游戏。"],
  ["cheyenne", "夏安", "Cheyenne", "Exidy", 1985, "Exidy推出的光枪射击游戏。"],
  ["chicken-shift", "小鸡移位", "Chicken Shift", "Jaleco", 1984, "益智游戏。"],
  ["clay-pigeon", "泥鸽", "Clay Pigeon", "Exidy", 1981, "光枪射击游戏。"],
  ["dari", "达利", "Dari", "Sega", 1987, "纵版射击游戏。"],
  ["dari-ii", "达利II", "Dari II", "Sega", 1988, "纵版射击游戏。"],
  ["dirt-fox", "越野狐狸", "Dirt Fox", "Namco", 1989, "Namco推出的越野赛车游戏。"],
  ["double-axle", "双轴", "Double Axle", "Sega", 1990, "赛车游戏。"],
  ["dragon-bter", "龙战士", "Dragon Buster", "Namco", 1984, "Namco推出的横版动作游戏，玩家扮演屠龙勇士。"],
  ["enforce", "强制执行", "Enforce", "Taito", 1989, "Taito推出的机甲射击游戏。"],
  ["espial", "ESP战机", "Espial", "Orca", 1983, "纵版射击游戏。"],
  ["eyes", "眼睛", "Eyes", "Sega", 1983, "迷宫游戏。"],
  ["flying-shark", "飞鲨", "Flying Shark", "Toaplan", 1987, "Toaplan推出的纵版射击游戏。"],
  ["funky-jet", "喷射战机", "Funky Jet", "Mitchell", 1992, "Mitchell推出的横版射击游戏。"],
  ["future-spy", "未来间谍", "Future Spy", "Sega", 1984, "Sega推出的射击游戏。"],
  ["gang-bters", "流氓克星", "Gang Busters", "Konami", 1988, "Konami推出的俯视角射击游戏。"],
  ["gundhara", "群蛇", "Gundhara", "Allumer", 1989, "纵版射击游戏。"],
  ["hammerin-harry", "锤子哈里", "Hammerin Harry", "Irem", 1990, "Irem推出的横版清关游戏，玩家用锤子打击敌人。"],
  ["kicker", "踢击", "Kicker", "Konami", 1986, "Konami推出的平台动作游戏。"],
  ["lost-tomb", "失落之墓", "Lost Tomb", "Stern", 1983, "Stern推出的射击游戏。"],
  ["mega-blast", "巨型爆破", "Mega Blast", "Taito", 1989, "射击游戏。"],
  ["mega-twins", "奇奇兄弟", "Mega Twins", "Capcom", 1990, "Capcom推出的横版动作游戏，双胞胎王子勇闯魔塔。"],
  ["mx5000", "MX5000", "MX5000", "Sega", 1991, "赛车游戏。"],
  ["osman", "奥斯曼", "Osman", "Capcom", 1995, "Capcom推出的横版动作游戏。"],
  ["puzz-loop-2", "谜之环2", "Puzz Loop 2", "Mitchell", 2001, "益智消除游戏续作。"],
  ["soldier-girl-amazon", "女战士亚马逊", "Soldier Girl Amazon", "Nichibutsu", 1985, "纵版射击游戏。"],
  ["tao-taido", "道太极", "Tao Taido", "Allumer", 1993, "格斗游戏。"],
  ["tazz-mania", "塔兹狂热", "Tazz-Mania", "Sega", 1989, "Sega推出的竞速游戏。"],
  ["wonder-planet", "神奇星球", "Wonder Planet", "Sega", 1990, "Sega推出的纵版射击游戏。"],
  ["hammerin-harry", "锤子哈里", "Hammerin Harry", "Irem", 1990, "Irem推出的横版平台动作游戏，玩家扮演木匠哈里用锤子打击敌人。"],
  ["vindicators", "复仇者", "Vindicators", "Atari", 1988, "Atari推出的未来风格坦克射击游戏，玩家驾驶坦克摧毁敌军基地。"],
  ["cameltry", "卡梅尔", "Cameltry", "Taito", 1989, "Taito推出的迷宫球体益智游戏，玩家倾斜迷宫引导球体到达终点。"],
  ["calipso", "卡利普索", "Calipso", "Taito", 1982, "Taito推出的固定射击游戏。"],
  ["blazer", "烈火", "Blazer", "Namco", 1987, "Namco推出的纵版射击游戏。"],
  ["blockade", "封锁", "Blockade", "Gremlin", 1976, "早期贪吃蛇类迷宫游戏。"],
  ["chanbara", "剑斗", "Chanbara", "Sega", 1985, "刀剑对战格斗游戏。"],
  ["cerber", "防卫犬", "Cerber", "Sega", 1986, "射击游戏。"],
  ["cheeky-moe", "淘气", "Cheeky Moe", "Sega", 1987, "横版射击游戏。"],
  ["chequered-flag", "方格旗", "Chequered Flag", "Sega", 1988, "赛车游戏。"],
  ["chuka-taisen", "中华大仙", "Chuka Taisen", "Toaplan", 1988, "纵版射击游戏，中国神话主题。"],
  ["cop-01", "警察01", "COP 01", "Sega", 1985, "射击游戏。"],
  ["crude-bter", "粗野斗士", "Crude Buster", "Data East", 1990, "横版清关游戏。"],
  ["cue-brick", "台球砖块", "Cue Brick", "Taito", 1988, "台球打砖块游戏。"],
  ["dambters", "大坝战士", "Dambusters", "Sega", 1986, "纵版轰炸游戏。"],
  ["driving-force", "驾训", "Driving Force", "Sega", 1990, "赛车游戏。"],
  ["gunnail", "炮钉", "Gunnail", "NMK", 1993, "纵版射击游戏。"],
  ["jump-shot", "跳投", "Jump Shot", "Sega", 1985, "篮球游戏。"],
  ["jyangokhi-haoh-no-saihai", "雀豪", "Jyangokhi", "Seta", 1993, "麻将游戏。"],
  ["knuckle-bash", "拳斗", "Knuckle Bash", "Sega", 1992, "摔跤游戏。"],
  ["mars-matrix", "火星矩阵", "Mars Matrix", "Capcom", 2000, "纵版弹幕射击游戏，吸收子弹能量攻击。"],
  ["meta-fox", "超狐", "Meta Fox", "Sega", 1988, "射击游戏。"],
  ["pnickies", "弹珠", "Pnickies", "Capcom", 1994, "弹珠台益智游戏。"],
  ["ryu-jin", "龙神", "Ryu Jin", "Sega", 1990, "纵版射击游戏。"],
]

async function main() {
  for (const [slug, title, titleEn, dev, year, desc] of updates) {
    await p.game.update({ where: { slug }, data: { title, titleEn, developer: dev, releaseYear: year, description: desc } })
    console.log(`✅ ${slug}`)
  }
  await p.$disconnect()
}
main().catch(console.error)
